### ISSUE TITLE
MultiBit HD and private key

### ISSUE THREAD

**Issue by PawelLyszczorz** [keepkey/multibit-hd#925]
In older version (MultiBit not HD) was possibility of extracting private key. I know that policy has changed but this function would be very useful for some of users. I am not the only one who misses that. Could you add it to MultiBit HD?

MultiBit HD does not allow to migrate wallet to other wallet and use there.

**Comment by bgok** [comment]
There is not an export mechanism to extract private keys or the wallet seed. It was not added to Multibit HD because it is easy to make a mistake when handling a file with unencrypted key in it. Instead a mnemonic seed is used and the private keys are derived from that.

When you created your wallet, a seed was created and the application asked you to write it down the mnemonic words for the seed. This mnemonic can be used to recover your wallet on any wallet with a compatible BIP32 implementation. Additionally, the wallet file is standard bitcoinj wallet, so you should be able to open it with any other wallet that uses bitcoinj.

The recommended action, however, is to setup your new wallet with a new seed, then send your bitcoins from multibit to your new wallet.

**Comment by PawelLyszczorz** [comment]
I am interested in getting private keys because of AMP currency, not because of BTC, so I can't send it. I would like to import them at wallet which enables me to manage them like omniwallet.

Should I use this tool to extract private keys: https://dcpos.github.io/bip39/ ?

**Comment by bgok** [comment]
You can derive private keys from your seed with that tool. However, after you do, you should treat the seed and its private keys as if they were compromised. You should move all of the currencies and tokens to a new wallet immediately after you have recovered your AMP tokens.

**Comment by bitjoinstudios** [comment]
Hey @PawelLyszczorz did you ever get to the bottom of this issue?

**Comment by PawelLyszczorz** [comment]
Hi,

I'm really sorry for late response but I was very busy and fortunately
during Christmas I found some free time. I did it.

Very useful tutorial:
http://bitcoin.stackexchange.com/questions/46112/how-to-get-mutlibit-hd-private-keys-from-mnemonic

Key advices:
derivation path is m/0'/0 and no passphrase needed (even if you have wallet under password).

**Comment by PawelLyszczorz** [comment]
Here is better example, because I added also password:
timestamp - 2914/04
wallet words: obey addict zero famous clever flag case exile art country
giraffe bulb
password: test
One of addresses: 19hc3HCUksnUfGGtTciv8Tf5DfwxCqCwzi
I tried many options here - https://iancoleman.github.io/bip39/ , none of
them worked.

Regards
Pawel

2016-12-26 15:19 GMT+01:00 Paweł Łyszczorz <pawel.lyszczorz@gmail.com>:

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
